name: Go
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: centos:7.9.2009
      options: >-
        --privileged  # 允许容器内运行服务（如 MySQL）
        --env="http_proxy=$http_proxy"
        --env="https_proxy=$https_proxy"
    steps:
      - name: Stop default MySQL (容器内无 systemd，此步骤可删除)
        run: |
          echo "CentOS 容器中无需 systemctl 停止 MySQL"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install MySQL
        run: |
          # 安装 MySQL 依赖
          sudo yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-7.noarch.rpm
          sudo yum install -y mysql-community-server
          # 启动 MySQL
          sudo mysqld_safe --user=mysql &
          # 获取初始密码
          sleep 10
          INIT_PASSWORD=$(sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
          echo "Initial MySQL password: $INIT_PASSWORD"
          # 修改密码
          sudo mysql -uroot -p"$INIT_PASSWORD" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
          # 配置 MySQL
          sudo tee /etc/my.cnf <<EOF
  [mysqld]
  innodb_log_file_size=256MB
  innodb_buffer_pool_size=512MB
  max_allowed_packet=16MB
  max_connections=500
  log-bin=1
  server_id=222
  character_set_server=utf8mb4
  lower_case_table_names=1
  binlog-format = row
  gtid-mode = ON
  enforce_gtid_consistency = ON
  EOF
  sudo systemctl restart mysqld

- name: Verify MySQL Installation
  run: |
    mysql -uroot -p'root' -e 'SELECT version();'
    mysql -uroot -p'root' -e "SHOW VARIABLES WHERE Variable_name IN ('server_id', 'log_bin', 'lower_case_table_names', 'version');"

- name: Create Databases and User
  run: |
    mysql -uroot -p'root' -e "CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8;"
    mysql -uroot -p'root' -e "CREATE DATABASE IF NOT EXISTS test_inc DEFAULT CHARACTER SET utf8;"
    mysql -uroot -p'root' -e "CREATE USER test@'127.0.0.1' IDENTIFIED BY 'test';"
    mysql -uroot -p'root' -e "GRANT ALL ON *.* TO test@'127.0.0.1'; FLUSH PRIVILEGES;"

- name: Wait for MySQL to be ready
  run: |
    for i in {1..10}; do
      nc -z 127.0.0.1 3306 && echo "MySQL is ready" && exit 0
      echo -n "."
      sleep 2
    done
    echo "Failed to connect to MySQL" && exit 1

- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.22.1
  id: go

- name: Check out code
  uses: actions/checkout@v2

- name: Install pt-online-schema-change
  run: |
    sudo cp ./bin/pt-online-schema-change /usr/local/bin/
    sudo chmod +x /usr/local/bin/pt-online-schema-change
    sudo yum install -y perl-DBI perl-DBD-MySQL

- name: Install gh-ost
  run: |
    sudo wget -O gh-ost.tar.gz https://github.com/github/gh-ost/releases/download/v1.1.0/gh-ost-binary-linux-20200828140552.tar.gz
    sudo tar -zxvf gh-ost.tar.gz -C /usr/local/bin/
    sudo chmod +x /usr/local/bin/gh-ost

- name: Build & Test
  run: |
    sudo chmod +x cmd/explaintest/run-tests.sh
    make checklist gotest
